### PR TITLE
Add week 0

### PR DESCRIPTION
**Pull request by vsmart**
@jellea @socksy Have a look pls! 👀

### CODE REVIEW

**Comment by socksy** [comment]
Is this for the week leading up to the first project group?

**Comment by vsmart** [comment]
This is for next week. The first group after the workshop. @socksy

**Comment by vsmart** [comment]
ping

**Comment by socksy** [comment]
I think it's going to be exceedingly difficult to try and work out where we're going to stand until after the first meeting, so I don't really know if I have anything to add. I'm going to go ahead and merge since it seems what we have is good (though I suspect from the Nightcode troubles that we had in the workshop, that it could be setting up alternative work environments may be the main objective for a lot of people?).

**Pull request merged**
